#!/bin/bash
set -e

echo
echo '#'
echo '# This System Report was generated by: https://github.com/bitrise-docker/android-ndk/blob/master/system_report.sh'
echo '#  Pull Requests are welcome!'
echo '#'
echo

echo
echo "=== Revision / ID ======================"
if [ -z "$BITRISE_DOCKER_REV_NUMBER_ANDROID_NDK" ] ; then
  echo " [!] No BITRISE_DOCKER_REV_NUMBER_ANDROID_NDK defined!"
  exit 1
fi
echo "* BITRISE_DOCKER_REV_NUMBER_ANDROID_NDK: $BITRISE_DOCKER_REV_NUMBER_ANDROID_NDK"
echo "========================================"
echo
echo "$ cat $ANDROID_NDK_HOME/RELEASE.TXT"
cat "${ANDROID_NDK_HOME}/RELEASE.TXT"
echo
echo "$ tree -L 2 /opt/android-ndk"
tree -L 2 /opt/android-ndk
echo
